--liquibase formatted sql
--changeset ericsson:3.2.0-base-siteNr

-- ----------------------------
-- Table structure for siteNr
-- ----------------------------
DROP TABLE IF EXISTS `siteNr`;
CREATE TABLE `siteNr` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
  `city` varchar(50) DEFAULT NULL COMMENT 'city',
  `NRgNodeBID` int(11) DEFAULT NULL COMMENT 'gNBId',
  `NRcellLocalId` int(11) DEFAULT NULL COMMENT 'cellLocalId',
  `siteNameChinese` varchar(255) DEFAULT NULL COMMENT 'siteNameChinese',
  `O&MIP` varchar(255) DEFAULT NULL COMMENT 'O&MIP',
  `longitude` float(10,6) DEFAULT NULL COMMENT 'longitude',
  `latitude` float(10,6) DEFAULT NULL COMMENT 'latitude',
  `direction` int(11) DEFAULT NULL COMMENT 'direction',
  `cellType` varchar(20) DEFAULT NULL COMMENT 'cellType',
  `tiltM` int(11) DEFAULT NULL COMMENT 'tiltM',
  `antHeight` int(11) DEFAULT NULL COMMENT 'antHeight',
  `cellNameChinese` varchar(255) DEFAULT NULL COMMENT 'cellNameChinese',
  `hst` varchar(255) DEFAULT NULL COMMENT 'hst',
  `cluster` varchar(255) DEFAULT NULL COMMENT 'cluster',
  `district` varchar(255) DEFAULT NULL COMMENT 'district',
  `coverageType` varchar(255) DEFAULT NULL COMMENT 'coverageType',
  `currentENM` varchar(255) DEFAULT NULL COMMENT 'currentENM',
  `siteName` varchar(255) DEFAULT NULL COMMENT 'siteName',
  `cellName` varchar(255) DEFAULT NULL COMMENT 'cellName',
  `cellUserlabel` text DEFAULT NULL COMMENT 'cellUserlabel',
  `siteCellName` text DEFAULT NULL COMMENT 'siteCellName',
  `subNetwork` varchar(255) DEFAULT NULL COMMENT 'subNetwork',
  `cgi` varchar(255) DEFAULT NULL COMMENT 'cgi',
  `nci` varchar(255) DEFAULT NULL COMMENT 'nci',
  `duplexMode` varchar(255) DEFAULT NULL COMMENT 'duplexMode',
  `anchorSite` varchar(255) DEFAULT NULL COMMENT 'anchorSite',
  `anchorCell` varchar(255) DEFAULT NULL COMMENT 'anchorCell',
  `scs` varchar(255) DEFAULT NULL COMMENT 'scs',
  `NRRSI` varchar(255) DEFAULT NULL COMMENT 'rsi',
  `nRTAC` varchar(255) DEFAULT NULL COMMENT 'nRTAC',
  `nRPCI` varchar(255) DEFAULT NULL COMMENT 'nRPCI',
  `NRFrequencySSB` varchar(255) DEFAULT NULL COMMENT 'ssbFrequency',
  `tiltE` int(11) DEFAULT NULL COMMENT 'tiltE',
  `band` varchar(255) DEFAULT NULL COMMENT 'band',
  `channelBandWidth` int(11) DEFAULT NULL COMMENT 'channelBandWidth',
  `highTraffic` varchar(255) DEFAULT NULL COMMENT 'highTraffic',
  `highInterference` varchar(255) DEFAULT NULL COMMENT 'highInterference',
  `manageStatus` varchar(255) DEFAULT NULL COMMENT 'manageStatus',
  `activeStatus` varchar(255) DEFAULT NULL COMMENT 'activeStatus',
  `duName` varchar(255) DEFAULT NULL COMMENT 'duName',
  `rruName` varchar(255) DEFAULT NULL COMMENT 'rruName',
  `cabinetName` varchar(255) DEFAULT NULL COMMENT 'cabinetName',
  `formatRSI` varchar(30) DEFAULT NULL COMMENT 'formatRSI',
  `importDate` date DEFAULT NULL COMMENT 'importDate',
  `operator` varchar(255) DEFAULT NULL COMMENT 'operator',
  `deptId` int(11) DEFAULT NULL COMMENT '部门id',
  `cityCn` varchar(255) DEFAULT NULL COMMENT '城市中文名',
  PRIMARY KEY (`id`),
  UNIQUE KEY `cgi` (`cgi`) USING BTREE,
  KEY `SiteName` (`siteName`) USING BTREE,
  KEY `O&MIP` (`O&MIP`) USING BTREE,
  KEY `city` (`city`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='5G站点信息表';
