--liquibase formatted sql
--changeset ericsson:3.2.0-base-siteLte

-- ----------------------------
-- Table structure for siteLte
-- ----------------------------
DROP TABLE IF EXISTS `siteLte`;
CREATE TABLE `siteLte` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
  `city` varchar(50) DEFAULT '' COMMENT 'city',
  `O&MIP` varchar(50) DEFAULT '' COMMENT 'O&MIP',
  `cellName` varchar(255) DEFAULT '' COMMENT 'cellName',
  `cellUserlabel` text DEFAULT NULL COMMENT 'cellUserlabel',
  `siteCellName` text DEFAULT NULL COMMENT 'siteCellName',
  `siteName` varchar(255) DEFAULT '' COMMENT 'siteName',
  `siteNameChinese` varchar(255) DEFAULT '' COMMENT 'siteNameChinese',
  `longitude` float(10,6) DEFAULT NULL COMMENT 'longitude',
  `latitude` float(10,6) DEFAULT NULL COMMENT 'latitude',
  `direction` int(11) DEFAULT NULL COMMENT 'direction',
  `cellType` varchar(50) DEFAULT '' COMMENT 'cellType',
  `tiltM` int(11) DEFAULT NULL COMMENT 'tiltM',
  `tiltE` int(11) DEFAULT NULL COMMENT 'tiltE',
  `antHeight` int(11) DEFAULT NULL COMMENT 'antHeight',
  `cellNameChinese` varchar(255) DEFAULT '' COMMENT 'cellNameChinese',
  `ecgi` varchar(50) DEFAULT NULL COMMENT 'ecgi',
  `eNBId` varchar(30) DEFAULT NULL COMMENT 'eNBId',
  `cellId` varchar(30) DEFAULT NULL COMMENT 'cellId',
  `eci` varchar(50) DEFAULT NULL COMMENT 'eci',
  `rsi` varchar(30) DEFAULT NULL COMMENT 'rsi',
  `tac` varchar(30) DEFAULT NULL COMMENT 'tac',
  `pci` varchar(30) DEFAULT NULL COMMENT 'pci',
  `earfcn` int(30) DEFAULT NULL COMMENT 'earfcn',
  `dualBandNetwork` varchar(10) DEFAULT '' COMMENT 'dualBandNetwork',
  `duplexMode` varchar(30) DEFAULT '' COMMENT 'duplexMode',
  `caNetwork` varchar(10) DEFAULT '' COMMENT 'caNetwork',
  `band` varchar(20) DEFAULT '' COMMENT 'band',
  `channelBandWidth` int(11) DEFAULT NULL COMMENT 'channelBandWidth',
  `noofTxAntennasSite` varchar(30) DEFAULT '' COMMENT 'noofTxAntennasSite',
  `coverageType` varchar(100) DEFAULT '' COMMENT 'coverageType',
  `MIMO-UL` varchar(100) DEFAULT NULL COMMENT 'MIMO-UL',
  `MIMO-DL` varchar(100) DEFAULT NULL COMMENT 'MIMO-DL',
  `highTraffic` varchar(10) DEFAULT '' COMMENT 'highTraffic',
  `highInterference` varchar(10) DEFAULT '' COMMENT 'highInterference',
  `hst` varchar(10) DEFAULT '' COMMENT 'hst',
  `cluster` varchar(50) DEFAULT '' COMMENT 'cluster',
  `subNetwork` varchar(255) DEFAULT '' COMMENT 'subNetwork',
  `currentENM` varchar(255) DEFAULT '' COMMENT 'currentENM',
  `status` varchar(30) DEFAULT '' COMMENT 'status',
  `validAnchorCell` varchar(10) DEFAULT NULL COMMENT 'validAnchorCell',
  `basicIntelligentConnectivity` varchar(30) DEFAULT '' COMMENT 'basicIntelligentConnectivity',
  `operator` varchar(255) DEFAULT NULL COMMENT 'operator',
  `importDate` date DEFAULT NULL COMMENT 'importDate',
  `deptId` int(11) DEFAULT NULL COMMENT '地区id',
  `cityCn` varchar(255) DEFAULT NULL COMMENT '城市中文名',
  PRIMARY KEY (`id`),
  UNIQUE KEY `ecgi` (`ecgi`) USING BTREE,
  KEY `CellName` (`cellName`) USING BTREE,
  KEY `ip` (`O&MIP`) USING BTREE,
  KEY `siteName` (`siteName`) USING BTREE,
  KEY `city` (`city`) USING BTREE,
  KEY `earfcn` (`earfcn`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='4G站点信息表';
